### ISSUE TITLE
`executionSettings` requires update for execution on Spark/Databricks: `tempEmulationSchema`

### ISSUE THREAD

**Issue by jshoughtaling** [ohdsi-studies/HowOften#10]
The `tempEmulationSchema` argument needs to be set in `executionSettings` if you're running the package against a spark/Databricks db.

I updated the [CodeToRun.R](https://github.com/ohdsi-studies/HowOften/blob/516a174fc18fedfbb5117b2851522f983cd42e7c/StrategusCodeToRun.R#L23) for proper execution:

```r
executionSettings <- Strategus::createCdmExecutionSettings(
  connectionDetailsReference = connectionDetailsReference,
  workDatabaseSchema = workDatabaseSchema,
  cdmDatabaseSchema = cdmDatabaseSchema,
  cohortTableNames = CohortGenerator::getCohortTableNames(cohortTable = cohortTableName),
  workFolder = file.path(outputLocation, connectionDetailsReference, "strategusWork"),
  resultsFolder = file.path(outputLocation, connectionDetailsReference, "strategusOutput"),
  minCellCount = minCellCount,
  tempEmulationSchema = "<your temp schema>"
)
```

**Comment by chrisknoll** [comment]
You can also specify your own options("sqlRenderTempEmulationSchema") to set the value. This is easier than changing the package definition.

See: https://github.com/OHDSI/Strategus/blob/00d0c0025e252c8cf2c0aaaffdda31057f93bb67/R/Settings.R#L109C72-L109C102
