### ISSUE TITLE
Encoding issue with cohort name in `howoften_overall.json`: cohortID 780

### ISSUE THREAD

**Issue by jshoughtaling** [ohdsi-studies/HowOften#11]
We were unable to launch the `howoften_overall.json` execution due to unknown UTF-8 character. 

The issue is in the following cohort name for cohort 780:

`Raynaud�s disease or Raynaud�s phenomenon`

The name appears in two places in the json file, and replacing the � with an apostrophe resolves the issue.

**Comment by chrisknoll** [comment]
This should be fixed in latest commit.  Please pull down the updated file to get the change, or you can modify the JSON locally to remove the smart quotes (and replace with ' ).
